# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'day_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(305, 422)
        Form.setStyleSheet("QWidget#Form{\n"
"background-color: rgba(72, 72, 72, 60);\n"
"border: 2px solid black; \n"
"border-radius: 30px;}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dateLabel = QtWidgets.QLabel(Form)
        self.dateLabel.setStyleSheet("font: 12pt \"Franklin Gothic Medium\";\n"
"color: black;")
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.verticalLayout.addWidget(self.dateLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.imageWidget = QtWidgets.QWidget(Form)
        self.imageWidget.setObjectName("imageWidget")
        self.horizontalLayout.addWidget(self.imageWidget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.temperatureLabel = QtWidgets.QLabel(Form)
        self.temperatureLabel.setStyleSheet("font: 10pt \"Franklin Gothic Medium\";\n"
"color: black;")
        self.temperatureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.verticalLayout.addWidget(self.temperatureLabel)
        self.precipitationLabel = QtWidgets.QLabel(Form)
        self.precipitationLabel.setStyleSheet("font: 10pt \"Franklin Gothic Medium\";\n"
"color: black;")
        self.precipitationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.precipitationLabel.setObjectName("precipitationLabel")
        self.verticalLayout.addWidget(self.precipitationLabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.windSpeedLabel = QtWidgets.QLabel(Form)
        self.windSpeedLabel.setStyleSheet("font: 9pt \"Franklin Gothic Medium\";\n"
"color: black;")
        self.windSpeedLabel.setObjectName("windSpeedLabel")
        self.horizontalLayout_5.addWidget(self.windSpeedLabel)
        self.windDirectionLabel = QtWidgets.QLabel(Form)
        self.windDirectionLabel.setStyleSheet("font: 9pt \"Franklin Gothic Medium\";\n"
"color: black;")
        self.windDirectionLabel.setObjectName("windDirectionLabel")
        self.horizontalLayout_5.addWidget(self.windDirectionLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pressureLabel = QtWidgets.QLabel(Form)
        self.pressureLabel.setStyleSheet("font: 9pt \"Franklin Gothic Medium\";\n"
"color: black;")
        self.pressureLabel.setObjectName("pressureLabel")
        self.horizontalLayout_2.addWidget(self.pressureLabel)
        self.humidityLabel = QtWidgets.QLabel(Form)
        self.humidityLabel.setStyleSheet("font: 9pt \"Franklin Gothic Medium\";\n"
"color: black;")
        self.humidityLabel.setObjectName("humidityLabel")
        self.horizontalLayout_2.addWidget(self.humidityLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dateLabel.setText(_translate("Form", "Date and time"))
        self.temperatureLabel.setText(_translate("Form", "Temperature"))
        self.precipitationLabel.setText(_translate("Form", "Precipitation chance"))
        self.windSpeedLabel.setText(_translate("Form", "Wind speed: "))
        self.windDirectionLabel.setText(_translate("Form", "Wind direction: "))
        self.pressureLabel.setText(_translate("Form", "Pressure: "))
        self.humidityLabel.setText(_translate("Form", "Humidity: "))
